### ISSUE TITLE
In a prerelease org the CRM and Site calendar isn’t displaying Volunteer Shifts on the monthly view.

### ISSUE THREAD

**Issue by yiselhernandezSF** [SalesforceFoundation/Volunteers-for-Salesforce#506] opened 2021-02-09 21:58 UTC
**Issue:**
In a prerelease org (Spring release from Core) the CRM and Site calendar isn’t displaying Volunteer Shifts on the monthly view, however it's working as expected on the weekly and daily views.

<img width="1421" alt="Screen Shot 2021-02-09 at 5 02 08 PM" src="https://user-images.githubusercontent.com/71083216/107432758-2c78f600-6b07-11eb-929e-c018851d3589.png">
<img width="1411" alt="Screen Shot 2021-02-09 at 5 02 28 PM" src="https://user-images.githubusercontent.com/71083216/107432775-31d64080-6b07-11eb-9d73-95477bbf8334.png">

**Steps to reproduce:**
_CRM_
1 - In an prerelease org with V4S Select Volunteers in App Launcher.
2- Navigate to Shift Calendar tab.
3- Select monthly view.

Expected: Volunteer Shifts should be displayed correctly.
Actual Result: Calendar isn’t displaying Volunteer Shifts on the monthly view.

_Site_
1- Go to the URL for your site and add /GW_Volunteers__JobCalendar to it.
2- Select monthly view.

Expected: Volunteer Shifts should be displayed correctly.
Actual Result: Calendar isn’t displaying Volunteer Shifts on the monthly view.

WI in GUS: [W-8870852](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B00000096DVEIA2/view)

**Comment by scottwarren-sfdo** [comment] 2021-04-09 18:15
No longer applicable as feature change has been rolled back. As a result, the issue is no longer reproducible. Closing.

**Closed by scottwarren-sfdo** 2021-04-09 18:15 UTC
