### ISSUE TITLE
V4S: VolunteersSignupFS page broken if using FileUploadLabel URL parameter

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Volunteers-for-Salesforce#336] opened 2018-01-15 20:00 UTC
hub thread: https://powerofus.force.com/0D58000003vC6IG

user is reporting getting the error: 
apex:inputFile can not be used in conjunction with an action component, apex:commandButton or apex:commandLink that specifies a rerender or oncomplete attribute.

this error is likely due to either a change in what Salesforce supports for file uploading, or in how V4S was handling updates on its page.

**Comment by davidhabib** [comment] 2018-01-15 20:01
**lurch: add

**Comment by LurchTheButler** [comment] 2018-01-15 20:05
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009KC7CAAW" target="_blank">W-022138</a>

**Comment by JuliaKhonUna** [comment] 2018-07-22 02:45
Hello Salesforce, 
is there any update on this bug? Any suggested workarounds? Help is appreciated.

**Comment by jesslopez-sf** [comment] 2019-04-23 18:08
Duplicate of https://github.com/SalesforceFoundation/Volunteers-for-Salesforce/issues/282

**Closed by jesslopez-sf** 2019-04-23 18:08 UTC
